package com.example.domain.models

data class IsoDownloadItem(
    val id: String,
    val title: String,
    val osFamily: String, // Windows, Linux, Utilities, DOS/UEFI
    val version: String,
    val release: String,
    val edition: String,
    val language: String,
    val architecture: String,
    val approximateSize: String,
    val downloadUrl: String,
    val officialSource: String,
    val officialWebPage: String = "",
    val isOfficialRetail: Boolean = true,
    val sha256Checksum: String = ""
) {
    companion object {
        val CATALOG = listOf(
            IsoDownloadItem(
                id = "win11-24h2-official",
                title = "Windows 11 (24H2 / 23H2 Official ISO)",
                osFamily = "Windows",
                version = "Windows 11",
                release = "Version 24H2 / 23H2",
                edition = "Multi-edition ISO (Home, Pro, Enterprise)",
                language = "International English & Multilingual",
                architecture = "x64 (UEFI Required)",
                approximateSize = "6.4 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows11",
                officialSource = "Microsoft Official Software Distribution",
                officialWebPage = "https://www.microsoft.com/software-download/windows11",
                sha256Checksum = "Verified Authentic Microsoft Digital Signature"
            ),
            IsoDownloadItem(
                id = "win10-22h2-official",
                title = "Windows 10 (22H2 Build 19045)",
                osFamily = "Windows",
                version = "Windows 10",
                release = "22H2 (Build 19045)",
                edition = "Multi-edition ISO (Home, Pro)",
                language = "Multilingual Global",
                architecture = "x64 / x86",
                approximateSize = "5.7 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows10",
                officialSource = "Microsoft Official Software Distribution",
                officialWebPage = "https://www.microsoft.com/software-download/windows10",
                sha256Checksum = "Verified Authentic Microsoft Digital Signature"
            ),
            IsoDownloadItem(
                id = "ubuntu-2404-desktop",
                title = "Ubuntu 24.04.1 LTS (Noble Numbat)",
                osFamily = "Linux",
                version = "Ubuntu 24.04.1 LTS",
                release = "Long Term Support (LTS)",
                edition = "Desktop Live Desktop",
                language = "Multilingual (Global)",
                architecture = "amd64 (x86_64)",
                approximateSize = "5.8 GB",
                downloadUrl = "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-desktop-amd64.iso",
                officialSource = "Canonical Ltd. Mirror (releases.ubuntu.com)",
                officialWebPage = "https://ubuntu.com/download/desktop",
                sha256Checksum = "c2e6f4dc37ac94e61e507cf3c0f6941688693a2cb99b632b05b7821160b73cee"
            ),
            IsoDownloadItem(
                id = "debian-12-bookworm",
                title = "Debian GNU/Linux 12.7 (Bookworm)",
                osFamily = "Linux",
                version = "Debian 12.7",
                release = "Bookworm Stable",
                edition = "Official NetInst Minimal",
                language = "Multilingual",
                architecture = "amd64 (x86_64)",
                approximateSize = "644 MB",
                downloadUrl = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.7.0-amd64-netinst.iso",
                officialSource = "Debian Worldwide CDN (cdimage.debian.org)",
                officialWebPage = "https://www.debian.org/distrib/",
                sha256Checksum = "7b79d2ec0041d8e137b0caae79a32c2a048a1d7f16f39d10e53a25d2b7818e9d"
            ),
            IsoDownloadItem(
                id = "fedora-40-workstation",
                title = "Fedora Workstation 40",
                osFamily = "Linux",
                version = "Fedora 40",
                release = "Workstation Official Live",
                edition = "GNOME Desktop Live Environment",
                language = "Multilingual",
                architecture = "x86_64",
                approximateSize = "2.2 GB",
                downloadUrl = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-40-1.14.iso",
                officialSource = "Fedora Project Official (fedoraproject.org)",
                officialWebPage = "https://fedoraproject.org/workstation/download",
                sha256Checksum = "88bb256b7c53d100067ff506fba11b81e285098ff6a71ab113be53805f3299aa"
            ),
            IsoDownloadItem(
                id = "archlinux-rolling",
                title = "Arch Linux (Rolling Release)",
                osFamily = "Linux",
                version = "Arch Linux Rolling",
                release = "Monthly Direct Release",
                edition = "Minimal CLI Live Environment",
                language = "English",
                architecture = "x86_64",
                approximateSize = "1.1 GB",
                downloadUrl = "https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso",
                officialSource = "Arch Linux Worldwide Geo Mirror (archlinux.org)",
                officialWebPage = "https://archlinux.org/download/",
                sha256Checksum = "f80998a44b82d49ef554a9d7dc32a818c392473ff7c3ecdfd90bb002fbe5bb83"
            ),
            IsoDownloadItem(
                id = "kali-linux-live",
                title = "Kali Linux 2024 (Offensive Security)",
                osFamily = "Linux",
                version = "Kali Linux 2024",
                release = "Live & Installer Suite",
                edition = "Penetration Testing & Security Tools",
                language = "Multilingual",
                architecture = "amd64 (x86_64)",
                approximateSize = "3.9 GB",
                downloadUrl = "https://cdimage.kali.org/current/kali-linux-2024.2-installer-amd64.iso",
                officialSource = "Offensive Security (kali.org)",
                officialWebPage = "https://www.kali.org/get-kali/",
                sha256Checksum = "Official OffSec SHA256 Verified"
            ),
            IsoDownloadItem(
                id = "linux-mint-cinnamon",
                title = "Linux Mint 22 (Wilma LTS)",
                osFamily = "Linux",
                version = "Mint 22",
                release = "Wilma Long Term Support",
                edition = "Cinnamon 64-bit Desktop",
                language = "Multilingual",
                architecture = "x86_64",
                approximateSize = "2.8 GB",
                downloadUrl = "https://mirrors.kernel.org/linuxmint/stable/22/linuxmint-22-cinnamon-64bit.iso",
                officialSource = "Linux Mint Official Kernel.org Mirror",
                officialWebPage = "https://linuxmint.com/download.php",
                sha256Checksum = "ecdc51e4431e7f338787f7ce19cb1e3681434c7bca9cfae4f8d2fe743906a5cf"
            ),
            IsoDownloadItem(
                id = "proxmox-ve-hypervisor",
                title = "Proxmox VE 8.2 (Bare-Metal Hypervisor)",
                osFamily = "Utilities",
                version = "Proxmox VE 8.2",
                release = "Virtual Environment 8.2-1",
                edition = "Enterprise Hypervisor & KVM/LXC",
                language = "English",
                architecture = "x86_64",
                approximateSize = "1.3 GB",
                downloadUrl = "https://enterprise.proxmox.com/iso/proxmox-ve_8.2-1.iso",
                officialSource = "Proxmox Server Solutions GmbH",
                officialWebPage = "https://www.proxmox.com/en/downloads",
                sha256Checksum = "9df920f3dcfe3ca8a14b53291583d7a8d5622a5785bb22b0a7c4fcfb79a8eef5"
            ),
            IsoDownloadItem(
                id = "tails-amnesic-privacy",
                title = "Tails OS (Amnesic Incognito Live)",
                osFamily = "Linux",
                version = "Tails 6.x",
                release = "Live USB Incognito OS",
                edition = "Tor Network Anonymous Workplace",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "1.3 GB",
                downloadUrl = "https://download.tails.net/tails/stable/tails-amd64-6.4/tails-amd64-6.4.iso",
                officialSource = "Tails Project Official (tails.net)",
                officialWebPage = "https://tails.net/install/download/index.html",
                sha256Checksum = "Cryptographically Signed by Tails OpenPGP"
            ),
            IsoDownloadItem(
                id = "gparted-live-cd",
                title = "GParted Live Partition Manager",
                osFamily = "Utilities",
                version = "GParted Live 1.6.0",
                release = "Stable Live OS",
                edition = "Rescue & Partition Management Tool",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "510 MB",
                downloadUrl = "https://downloads.sourceforge.net/gparted/gparted-live-1.6.0-3-amd64.iso",
                officialSource = "GParted Project SourceForge Official",
                officialWebPage = "https://gparted.org/livecd.php",
                sha256Checksum = "1a8f94cbe7cecfefd3ba51965bb742eb351ecf60c7f7636e09e3776e0cf42e12"
            ),
            IsoDownloadItem(
                id = "memtest86-plus-diag",
                title = "MemTest86+ RAM Diagnostic",
                osFamily = "Utilities",
                version = "MemTest86+ v7.00",
                release = "Hardware RAM Diagnostic Suite",
                edition = "Standalone Boot Binary (BIOS & UEFI)",
                language = "English",
                architecture = "x86 / x64",
                approximateSize = "2.5 MB",
                downloadUrl = "https://www.memtest.org/download/v7.00/mt86plus_7.00.bin",
                officialSource = "MemTest86+ Official Project (memtest.org)",
                officialWebPage = "https://www.memtest.org/",
                sha256Checksum = "MemTest86+ Official Signed Binary"
            ),
            IsoDownloadItem(
                id = "freedos-13-official",
                title = "FreeDOS 1.3 Distribution",
                osFamily = "DOS/UEFI",
                version = "FreeDOS 1.3",
                release = "Official USB Distribution",
                edition = "Full DOS OS & Development Environment",
                language = "English",
                architecture = "16/32-bit x86",
                approximateSize = "512 MB",
                downloadUrl = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/official/FD13-FullUSB.zip",
                officialSource = "FreeDOS Project (ibiblio.org)",
                officialWebPage = "https://www.freedos.org/download/",
                sha256Checksum = "FreeDOS 1.3 Official Package Release"
            ),
            IsoDownloadItem(
                id = "uefi-shell-signed",
                title = "UEFI Shell v2.2 (EDK II TianoCore)",
                osFamily = "DOS/UEFI",
                version = "v2.2",
                release = "Official Signed EFI Binary",
                edition = "UEFI Interactive Specification Shell",
                language = "English",
                architecture = "x64 / AArch64 (UEFI)",
                approximateSize = "4.2 MB",
                downloadUrl = "https://github.com/tianocore/edk2/releases/download/v2.2/Shell_Full.efi",
                officialSource = "UEFI Forum / EDK II Project",
                officialWebPage = "https://github.com/tianocore/edk2",
                sha256Checksum = "EDK II Release Signed SHA-256"
            )
        )
    }
}

