package com.example.domain.models

data class IsoDownloadItem(
    val id: String,
    val title: String,
    val osFamily: String, // Windows, Linux, Utilities, DOS/UEFI
    val version: String,
    val release: String,
    val edition: String,
    val language: String,
    val architecture: String,
    val approximateSize: String,
    val downloadUrl: String,
    val officialSource: String,
    val officialWebPage: String = "",
    val isOfficialRetail: Boolean = true
) {
    companion object {
        val CATALOG = listOf(
            IsoDownloadItem(
                id = "win11-official-portal",
                title = "Windows 11 (Official ISO Portal)",
                osFamily = "Windows",
                version = "Windows 11",
                release = "23H2 / 24H2",
                edition = "Multi-edition (Home / Pro / Enterprise)",
                language = "All Languages (64-bit)",
                architecture = "x64 (UEFI Only)",
                approximateSize = "6.4 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows11",
                officialSource = "Microsoft Official Software Download Portal",
                officialWebPage = "https://www.microsoft.com/software-download/windows11"
            ),
            IsoDownloadItem(
                id = "win10-official-portal",
                title = "Windows 10 (Official ISO Portal)",
                osFamily = "Windows",
                version = "Windows 10",
                release = "22H2 (Build 19045)",
                edition = "Home / Pro / Enterprise",
                language = "Multilingual (Global)",
                architecture = "x64 / x86",
                approximateSize = "5.7 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows10",
                officialSource = "Microsoft Official Software Download Portal",
                officialWebPage = "https://www.microsoft.com/software-download/windows10"
            ),
            IsoDownloadItem(
                id = "ubuntu-24041-desktop",
                title = "Ubuntu 24.04.1 LTS Desktop",
                osFamily = "Linux",
                version = "Ubuntu 24.04.1",
                release = "Noble Numbat LTS",
                edition = "Desktop Live Image",
                language = "Multilingual (Global)",
                architecture = "amd64",
                approximateSize = "5.8 GB",
                downloadUrl = "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-desktop-amd64.iso",
                officialSource = "Canonical Ltd. (releases.ubuntu.com)",
                officialWebPage = "https://ubuntu.com/download/desktop"
            ),
            IsoDownloadItem(
                id = "ubuntu-22044-desktop",
                title = "Ubuntu 22.04.4 LTS Desktop",
                osFamily = "Linux",
                version = "Ubuntu 22.04.4",
                release = "Jammy Jellyfish LTS",
                edition = "Desktop Live Image",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "4.7 GB",
                downloadUrl = "https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-desktop-amd64.iso",
                officialSource = "Canonical Ltd. (releases.ubuntu.com)",
                officialWebPage = "https://ubuntu.com/download/desktop"
            ),
            IsoDownloadItem(
                id = "debian-1250-netinst",
                title = "Debian GNU/Linux 12.5",
                osFamily = "Linux",
                version = "Debian 12.5",
                release = "Bookworm NetInst",
                edition = "Official NetInst Minimal",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "628 MB",
                downloadUrl = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso",
                officialSource = "Debian Worldwide Direct CDN (cdimage.debian.org)",
                officialWebPage = "https://www.debian.org/distrib/"
            ),
            IsoDownloadItem(
                id = "fedora-40-workstation",
                title = "Fedora Workstation 40",
                osFamily = "Linux",
                version = "Fedora 40",
                release = "Workstation Live x86_64",
                edition = "GNOME Live Desktop",
                language = "Multilingual",
                architecture = "x86_64",
                approximateSize = "2.1 GB",
                downloadUrl = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-40-1.14.iso",
                officialSource = "Fedora Project (fedoraproject.org)",
                officialWebPage = "https://fedoraproject.org/workstation/download"
            ),
            IsoDownloadItem(
                id = "archlinux-latest",
                title = "Arch Linux (Rolling Release)",
                osFamily = "Linux",
                version = "Latest Rolling",
                release = "Monthly Official Release",
                edition = "Minimal Install Live Environment",
                language = "English / Neutral",
                architecture = "x86_64",
                approximateSize = "1.1 GB",
                downloadUrl = "https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso",
                officialSource = "Arch Linux Geo Mirror (archlinux.org)",
                officialWebPage = "https://archlinux.org/download/"
            ),
            IsoDownloadItem(
                id = "kali-linux-20242",
                title = "Kali Linux 2024.2 Installer",
                osFamily = "Linux",
                version = "Kali 2024.2",
                release = "Standard Installer ISO",
                edition = "Penetration Testing & Security",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "3.8 GB",
                downloadUrl = "https://cdimage.kali.org/kali-2024.2/kali-linux-2024.2-installer-amd64.iso",
                officialSource = "OffSec Kali Mirror (cdimage.kali.org)",
                officialWebPage = "https://www.kali.org/get-kali/"
            ),
            IsoDownloadItem(
                id = "linux-mint-213",
                title = "Linux Mint 21.3 Cinnamon",
                osFamily = "Linux",
                version = "Mint 21.3",
                release = "Virginia",
                edition = "Cinnamon 64-bit Desktop",
                language = "Multilingual",
                architecture = "64-bit",
                approximateSize = "2.9 GB",
                downloadUrl = "https://mirrors.kernel.org/linuxmint/stable/21.3/linuxmint-21.3-cinnamon-64bit.iso",
                officialSource = "Linux Mint Official Kernel.org Mirror",
                officialWebPage = "https://linuxmint.com/download.php"
            ),
            IsoDownloadItem(
                id = "proxmox-ve-82",
                title = "Proxmox VE 8.2 ISO Installer",
                osFamily = "Utilities",
                version = "Proxmox 8.2",
                release = "Virtual Environment 8.2-1",
                edition = "Bare-Metal Virtualization Hypervisor",
                language = "English",
                architecture = "x86_64",
                approximateSize = "1.3 GB",
                downloadUrl = "https://enterprise.proxmox.com/iso/proxmox-ve_8.2-1.iso",
                officialSource = "Proxmox Server Solutions GmbH",
                officialWebPage = "https://www.proxmox.com/en/downloads"
            ),
            IsoDownloadItem(
                id = "tails-64-privacy",
                title = "Tails OS 6.4 (Amnesic Incognito Live)",
                osFamily = "Linux",
                version = "Tails 6.4",
                release = "Live USB Edition",
                edition = "Privacy & Tor Network Security OS",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "1.3 GB",
                downloadUrl = "https://download.tails.net/tails/stable/tails-amd64-6.4/tails-amd64-6.4.iso",
                officialSource = "Tails Project (tails.net)",
                officialWebPage = "https://tails.net/install/download/index.html"
            ),
            IsoDownloadItem(
                id = "gparted-live",
                title = "GParted Live 1.6.0-3",
                osFamily = "Utilities",
                version = "GParted 1.6.0",
                release = "Live Partition Manager",
                edition = "Standalone Disk Recovery OS",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "510 MB",
                downloadUrl = "https://downloads.sourceforge.net/gparted/gparted-live-1.6.0-3-amd64.iso",
                officialSource = "GParted Project SourceForge Official",
                officialWebPage = "https://gparted.org/livecd.php"
            ),
            IsoDownloadItem(
                id = "memtest86-plus",
                title = "MemTest86+ v7.00 RAM Diagnostic",
                osFamily = "Utilities",
                version = "v7.00",
                release = "RAM Hardware Diagnostic Tool",
                edition = "Bootable Binary (BIOS & UEFI)",
                language = "English",
                architecture = "x86 / x64",
                approximateSize = "2.5 MB",
                downloadUrl = "https://www.memtest.org/download/v7.00/mt86plus_7.00.bin",
                officialSource = "MemTest86+ Official (memtest.org)",
                officialWebPage = "https://www.memtest.org/"
            ),
            IsoDownloadItem(
                id = "freedos-13-full",
                title = "FreeDOS 1.3 Live USB",
                osFamily = "DOS/UEFI",
                version = "FreeDOS 1.3",
                release = "Full USB Distribution",
                edition = "Complete DOS OS with Developer Tools",
                language = "English",
                architecture = "16-bit / 32-bit x86",
                approximateSize = "512 MB",
                downloadUrl = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/official/FD13-FullUSB.zip",
                officialSource = "FreeDOS Project Official Mirror (ibiblio.org)",
                officialWebPage = "https://www.freedos.org/download/"
            ),
            IsoDownloadItem(
                id = "uefi-shell-22",
                title = "UEFI Shell v2.2 (EDK II TianoCore)",
                osFamily = "DOS/UEFI",
                version = "v2.2",
                release = "Official Signed EFI Binary",
                edition = "Full UEFI Shell Spec (x64)",
                language = "English",
                architecture = "x64 / AArch64",
                approximateSize = "4.2 MB",
                downloadUrl = "https://github.com/tianocore/edk2/releases/download/v2.2/Shell_Full.efi",
                officialSource = "UEFI Forum / EDK II Official",
                officialWebPage = "https://github.com/tianocore/edk2"
            )
        )
    }
}
