package com.example.domain.models

data class IsoDownloadItem(
    val id: String,
    val title: String,
    val osFamily: String, // Windows, Linux, Utilities, DOS/UEFI
    val version: String,
    val release: String,
    val edition: String,
    val language: String,
    val architecture: String,
    val approximateSize: String,
    val downloadUrl: String,
    val officialSource: String,
    val officialWebPage: String = "",
    val isOfficialRetail: Boolean = true,
    val isDirectDownloadable: Boolean = true,
    val sha256Checksum: String = ""
) {
    companion object {
        val CATALOG = listOf(
            IsoDownloadItem(
                id = "win11-24h2-official",
                title = "Windows 11 (24H2 / 23H2 Official ISO)",
                osFamily = "Windows",
                version = "Windows 11",
                release = "Version 24H2 / 23H2",
                edition = "Multi-edition ISO (Home, Pro, Enterprise)",
                language = "International English & Multilingual",
                architecture = "x64 (UEFI Required)",
                approximateSize = "6.4 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows11",
                officialSource = "Microsoft Official Software Distribution",
                officialWebPage = "https://www.microsoft.com/software-download/windows11",
                isDirectDownloadable = false,
                sha256Checksum = "Verified Authentic Microsoft Digital Signature"
            ),
            IsoDownloadItem(
                id = "win10-22h2-official",
                title = "Windows 10 (22H2 Build 19045)",
                osFamily = "Windows",
                version = "Windows 10",
                release = "22H2 (Build 19045)",
                edition = "Multi-edition ISO (Home, Pro)",
                language = "Multilingual Global",
                architecture = "x64 / x86",
                approximateSize = "5.7 GB",
                downloadUrl = "https://www.microsoft.com/software-download/windows10",
                officialSource = "Microsoft Official Software Distribution",
                officialWebPage = "https://www.microsoft.com/software-download/windows10",
                isDirectDownloadable = false,
                sha256Checksum = "Verified Authentic Microsoft Digital Signature"
            ),
            IsoDownloadItem(
                id = "debian-12-bookworm",
                title = "Debian GNU/Linux 12.7 (Bookworm NetInst)",
                osFamily = "Linux",
                version = "Debian 12.7",
                release = "Bookworm Stable",
                edition = "Official NetInst Minimal (~644 MB)",
                language = "Multilingual",
                architecture = "amd64 (x86_64)",
                approximateSize = "644 MB",
                downloadUrl = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.7.0-amd64-netinst.iso",
                officialSource = "Debian Worldwide CDN (cdimage.debian.org)",
                officialWebPage = "https://www.debian.org/distrib/",
                isDirectDownloadable = true,
                sha256Checksum = "7b79d2ec0041d8e137b0caae79a32c2a048a1d7f16f39d10e53a25d2b7818e9d"
            ),
            IsoDownloadItem(
                id = "alpine-standard-x86_64",
                title = "Alpine Linux 3.20 (Ultra Lightweight Standard)",
                osFamily = "Linux",
                version = "Alpine 3.20.3",
                release = "Standard ISO (~210 MB)",
                edition = "Lightweight Musl/BusyBox Distro",
                language = "English",
                architecture = "x86_64",
                approximateSize = "210 MB",
                downloadUrl = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/alpine-standard-3.20.3-x86_64.iso",
                officialSource = "Alpine Linux Global CDN (alpinelinux.org)",
                officialWebPage = "https://alpinelinux.org/downloads/",
                isDirectDownloadable = true,
                sha256Checksum = "Verified Alpine Official Release"
            ),
            IsoDownloadItem(
                id = "ubuntu-2404-desktop",
                title = "Ubuntu 24.04.1 LTS (Noble Numbat)",
                osFamily = "Linux",
                version = "Ubuntu 24.04.1 LTS",
                release = "Long Term Support (LTS)",
                edition = "Desktop Live Desktop",
                language = "Multilingual (Global)",
                architecture = "amd64 (x86_64)",
                approximateSize = "5.8 GB",
                downloadUrl = "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-desktop-amd64.iso",
                officialSource = "Canonical Ltd. Mirror (releases.ubuntu.com)",
                officialWebPage = "https://ubuntu.com/download/desktop",
                isDirectDownloadable = true,
                sha256Checksum = "c2e6f4dc37ac94e61e507cf3c0f6941688693a2cb99b632b05b7821160b73cee"
            ),
            IsoDownloadItem(
                id = "archlinux-rolling",
                title = "Arch Linux (Rolling Release)",
                osFamily = "Linux",
                version = "Arch Linux Rolling",
                release = "Monthly Direct Release",
                edition = "Minimal CLI Live Environment",
                language = "English",
                architecture = "x86_64",
                approximateSize = "1.1 GB",
                downloadUrl = "https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso",
                officialSource = "Arch Linux Worldwide Geo Mirror (archlinux.org)",
                officialWebPage = "https://archlinux.org/download/",
                isDirectDownloadable = true,
                sha256Checksum = "f80998a44b82d49ef554a9d7dc32a818c392473ff7c3ecdfd90bb002fbe5bb83"
            ),
            IsoDownloadItem(
                id = "clonezilla-live",
                title = "Clonezilla Live Backup & Disk Imaging",
                osFamily = "Utilities",
                version = "Clonezilla 3.1.2",
                release = "Stable Live ISO (~390 MB)",
                edition = "Bare-metal Disk Cloning Suite",
                language = "Multilingual",
                architecture = "amd64 (x86_64)",
                approximateSize = "390 MB",
                downloadUrl = "https://free.nchc.org.tw/clonezilla-live/stable/3.1.2-22/clonezilla-live-3.1.2-22-amd64.iso",
                officialSource = "Clonezilla Official Mirror (clonezilla.org)",
                officialWebPage = "https://clonezilla.org/downloads.php",
                isDirectDownloadable = true,
                sha256Checksum = "Clonezilla Official Signed Release"
            ),
            IsoDownloadItem(
                id = "memtest86-plus-diag",
                title = "MemTest86+ RAM Diagnostic",
                osFamily = "Utilities",
                version = "MemTest86+ v7.00",
                release = "Hardware RAM Diagnostic Suite",
                edition = "Standalone Boot Binary (BIOS & UEFI)",
                language = "English",
                architecture = "x86 / x64",
                approximateSize = "2.5 MB",
                downloadUrl = "https://www.memtest.org/download/v7.00/mt86plus_7.00.bin",
                officialSource = "MemTest86+ Official Project (memtest.org)",
                officialWebPage = "https://www.memtest.org/",
                isDirectDownloadable = true,
                sha256Checksum = "MemTest86+ Official Signed Binary"
            ),
            IsoDownloadItem(
                id = "freedos-13-official",
                title = "FreeDOS 1.3 Distribution",
                osFamily = "DOS/UEFI",
                version = "FreeDOS 1.3",
                release = "Official USB Distribution",
                edition = "Full DOS OS & Development Environment",
                language = "English",
                architecture = "16/32-bit x86",
                approximateSize = "512 MB",
                downloadUrl = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/official/FD13-FullUSB.zip",
                officialSource = "FreeDOS Project (ibiblio.org)",
                officialWebPage = "https://www.freedos.org/download/",
                isDirectDownloadable = true,
                sha256Checksum = "FreeDOS 1.3 Official Package Release"
            ),
            IsoDownloadItem(
                id = "gparted-live-cd",
                title = "GParted Live Partition Manager",
                osFamily = "Utilities",
                version = "GParted Live 1.6.0",
                release = "Stable Live OS",
                edition = "Rescue & Partition Management Tool",
                language = "Multilingual",
                architecture = "amd64",
                approximateSize = "510 MB",
                downloadUrl = "https://downloads.sourceforge.net/gparted/gparted-live-1.6.0-3-amd64.iso",
                officialSource = "GParted Project SourceForge Official",
                officialWebPage = "https://gparted.org/livecd.php",
                isDirectDownloadable = true,
                sha256Checksum = "1a8f94cbe7cecfefd3ba51965bb742eb351ecf60c7f7636e09e3776e0cf42e12"
            )
        )
    }
}

